# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sentinel detects and triggers the necessary configuration update, ensuring Kamal remains aware and correctly configured for its AWS environment.

Globals:
  Function:
    Timeout: 30 # Timeout for Lambda functions
    MemorySize: 128 # Memory for Lambda functions
    # Important: Set the runtime to 'provided.al2' (Amazon Linux 2)
    # as Bref provides the actual PHP runtime via layers.
    Runtime: provided.al2
    Architectures:
      - x86_64
    Environment:
      Variables:
        # environment variables
        AWS_REGION: us-east-1
        AWS_EVENT_BUS_NAME: default
        BREF_LAYER_AWS_ACCOUNT_ID: 534081306603
        
Resources:
  #1. Define the S3 Bucket - This bucket will be used by the Lambda function to read/write Kamal configuration.
  SentinelKamalConfigurationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sentinel-kamal-configuration-file-bucket
      VersioniningConfiguration:
        Status: Enabled

  #2. This is the Lambda function that will be trigger when the EC2 state change event happens
  SentinelKamalConfigurationUpdater:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: . # The entire project directory will be uploaded
      Handler: src/index.php # Entry point
      # Link to the Bref PHP runtime layer
      Layers:
        - !Sub "arn:aws:lambda:${AWS_REGION}:${BREF_LAYER_AWS_ACCOUNT_ID}:layer:php-84:26" # Use the latest PHP layer ARN for the region
      Policies:
        # Policy to grant the Lambda function read/write access to the S3 bucket.
        # This is an identity-based policy attached to the Lambda's execution role.
        - S3CrudPolicy: # SAM's managed policy for S3 Read/Write/List
            BucketName: !Ref SentinelKamalConfigurationBucket

        # Policy to grant the Lambda function permission to send messages to the SQS queue.
        # This is an identity-based policy attached to the Lambda's execution role.
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SentinelKamalConfigurationUpdateQueue.QueueName

        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: makefile

  #3. Eventbridge rule to capture EC2 state change notifications
  EC2InstanceStateChangeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: EC2InstanceStateChangeToSqsRule
      Description: "Routes EC2 instance state change notifications to an SQS queue."
      EventBusName: !Sub '${AWS_EVENT_BUS_NAME}'
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Instance State-Change Notification
        detail:
          state:
            - running
            - terminated
      Targets:
        - Id: SentinelKamalConfigurationUpdater # Logical ID for the target
          Arn: !GetAtt SentinelKamalConfigurationUpdater.Arn # ARN of lambda function

  #4. SQS queue where Kamal configuration file update job will be queued
  SentinelKamalConfigurationUpdateQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: sentinel-kamal-configuration-update-queue
      MessageRetentionPeriod: 21600 # Six hours
      VisibilityTimeout: 180 # 3 minutes (should be at least 6x the Lambda function's timeout)

  #5. Lambda function to file a PR to a configured source control
  # This lambda function is configured to poll messages from the
  # SentinelKamalConfigurationUpdateQueue. It sends a PR to the configured
  # source control repository.
  SentinelKamalConfigurationPullRequest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: . # The entire project directory will be uploaded
      Handler: src/index.php # Entry point
      # Link to the Bref PHP runtime layer
      Layers:
        - !Sub "arn:aws:lambda:${AWS_REGION}:${BREF_LAYER_AWS_ACCOUNT_ID}:layer:php-84:26" # Use the latest PHP layer ARN for the region
      Policies:
        # This policy grants the Lambda function permission to poll messages from the SQS queue.
        - SQSPollerPolicy:
            QueueName: !GetAtt SentinelKamalConfigurationUpdateQueue.QueueName
      Events:
        SentinelSqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SentinelKamalConfigurationUpdateQueue.Arn # Reference the ARN of the SQS queue defined above
            BatchSize: 1 # Number of messages to process per invocation
    Metadata:
      BuildMethod: makefile

Outputs:
  SentinelKamalConfigurationUpdaterArn:
    Description: "ARN of the SentinelKamalConfigurationUpdater function"
    Value: !GetAtt SentinelKamalConfigurationUpdater.Arn
  SentinelKamalConfigurationPullRequestArn:
    Description: "ARN of SentinelKamalConfigurationPullRequest function"
    Value: !GetAtt SentinelKamalConfigurationPullRequest.Arn
